//api REST de Municipios
@baseURL = http://localhost:3000/api/municipios
@id = 67cf89840f7b6deccb9065d2
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7ImlkIjoiNjgyMjg2YmQ5MzJjMWExZTI1ODYyNjE0In0sImlhdCI6MTc0NzA5ODM1MiwiZXhwIjoxNzQ3MTg0NzUyfQ.h6POWebd4q-xkdIbIw77S1sfMWdERtoNiOj5ua-xrys

###
//GET - By Id
GET {{baseURL}}/{{id}}
Content-Type: application/json
access-token: {{token}}

###
//GET - Id inválido
GET {{baseURL}}/3
Content-Type: application/json

###
//POST - Insere um novo municipio
POST {{baseURL}}
Content-Type: application/json

{  "codigo_ibge": 3100104,
  "nome": "Abadia dos DDDourados",
  "capital": true,
  "codigo_uf": 31,
  "local": {
    "type": "Point",
    "coordinates": [-47.3916, -18.4831]
  }
}