//api REST de Usuários
@baseURL = http://localhost:3000/api/usuarios
###
# @prompt senha 
POST {{baseURL}}
Content-Type: application/json

{
    "nome": "Albert Einstein",
    "email": "einstein@fatec.gov.br",
    "senha": "{{senha}}"
}
